version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

  app:
    build: .
    container_name: data_loader
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    entrypoint: ["python", "/app/scripts/load_json.py"]

volumes:
  postgres_data:
